pipeline:
  name: amster-build
  identifier: amsterbuild
  projectIdentifier: IDA
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: amster-build
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: api
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: setup
                  identifier: setup
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.9-amazoncorretto-17-al2023
                    shell: Sh
                    command: |-
                      pwd
                      ls -la /harness/amster-build/amster/samples/docker
                      /harness/amster-build/amster/samples/docker/setup.sh
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Nexus
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.Nexus
                    repo: 192.168.1.83:5000/repository/amster-base
                    tags: <+input>
                    dockerfile: <+input>
                    buildArgs:
                      APP_NAME: <+pipeline.name>
                    envVariables:
                      PLUGIN_SKIP_TLS_VERIFY: "true"
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1
          sharedPaths:
            - /gbshared
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
